#Main Config For Additions Addon.
lobby:
  adventure-mode: false
  level-bar:
    enabled: true
    permission:
      enabled: false
      node: "bwa.level-bar"
waiting:
  adventure-mode: true
  flight:
    enabled: false
    permission:
      enabled: true
      node: "bwa.flight"
  blindness:
    enabled: false
    bypass-permission:
      enabled: true
      node: "bwa.blindness.bypass"
  level-bar:
    enabled: false
    permission:
      enabled: false
      node: "bwa.level-bar"
in-game:
  level-bar:
    enabled: false
    permission:
      enabled: false
      node: "bwa.level-bar"
  unbreakable:
    enabled: true
    materials:
      #1.13+ Material ID
      - "DIAMOND_SWORD"
      - "IRON_SWORD"
      - "WOODEN_SWORD"
execute-command:
  enabled: true
  permission: "bwa.execute"
  no-permission: "&cYou don't have permission"
  player-not-found: "&cTarget player was not found"
  usage: "&aUsage: &f/execute <Player> <Command>"
messages:
  #message configuration
  prefix: "&c<< &fServer &c>> "
  command-no-permission: "&cYou don't have the appropriate permission to use this command"




